USE [master]
GO

/****** Object:  Database [QuanLyQuanAn]    Script Date: 27/12/2019 10:56:08 PM ******/
CREATE DATABASE [QuanLyQuanAn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyQuanAn', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\QuanLyQuanAn.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyQuanAn_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL2017\MSSQL\DATA\QuanLyQuanAn_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyQuanAn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLyQuanAn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLyQuanAn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLyQuanAn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QuanLyQuanAn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLyQuanAn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET RECOVERY FULL 
GO

ALTER DATABASE [QuanLyQuanAn] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLyQuanAn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLyQuanAn] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLyQuanAn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLyQuanAn] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLyQuanAn] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLyQuanAn] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QuanLyQuanAn] SET  READ_WRITE 
GO

